version: 1

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src/Plugins/Components.Support"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

  - package_manager: "javascript"
    directory: "/src/Components/TagPickerComponent"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"

  - package_manager: "javascript"
    directory: "/src/Components/TagPickerGridComponent"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:minor"